"""Copyright (c) {{ cookiecutter.__year }} {{ cookiecutter.full_name }}. All rights reserved.

{{ cookiecutter.project_name }}: {{ cookiecutter.project_short_description }}
"""
# flake8: noqa
# _version.py is autogenerated by setuptools_scm
from __future__ import annotations

from {{ cookiecutter.__project_slug }}._version import version as __version__

__all__ = ["__version__"]
