ci:
  autofix_prs: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      # https://github.com/pre-commit/pre-commit-hooks/issues/718
      # - id: check-added-large-files  # Fails with git v1.8.3
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: file-contents-sorter
        files: (requirements.txt)$
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: "23.7.0"
    hooks:
      - id: black
      - id: black-jupyter

  - repo: https://github.com/PyCQA/flake8
    rev: "6.1.0"
    hooks:
      - id: flake8

  - repo: https://github.com/PyCQA/isort
    rev: "5.12.0"
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.4.1"
    hooks:
      - id: mypy
        # additional_dependencies:

  - repo: https://github.com/PyCQA/pydocstyle
    rev: "6.3.0"
    hooks:
      - id: pydocstyle
        # https://github.com/PyCQA/pydocstyle/pull/608#issuecomment-1381168417
        additional_dependencies: ['.[toml]']
        exclude: tests
