# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2

mkdocs:
  configuration: mkdocs.yml

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  jobs:
    pre_install:
      - curl -fsSL https://pixi.sh/install.sh | bash
      - export PATH="$HOME/.pixi/bin:$PATH"
      - pixi install
    post_install:
      - pixi run pip install -e .[docs]
